# Generated by Django 4.2.4 on 2024-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_recuriter',
            new_name='is_recruiter',
        ),
    ]
